
name: Deploy 11ty to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci || npm i

      - name: Build 11ty
        run: npm run build   # génère dans site/docs

      - name: Upload artifact (docs)
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
/docs
cd ~/botcity-project/site
git status


# Assure-toi d’être dans le bon dossier
cd ~/botcity-project/site

# .eleventy.js -> sortie dans docs/
cat > .eleventy.js <<'EOF'
module.exports = { dir: { output: "docs" } };
EOF

# Workflow GitHub Actions
mkdir -p .github/workflows
cat > .github/workflows/deploy-pages.yml <<'EOF'
name: Deploy Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm install
      - name: Build site
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url 
}}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
EOF

