name: Link check
on:
  schedule: [{ cron: "0 6 * * 1" }]
  workflow_dispatch: {}

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: "--base . --no-progress --accept 200,204,206 --exclude-mail ./docs/**/*.html"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
